### ISSUE TITLE
脱退した人に何らかの条件があると、脱退回数を全部上書きしちゃう

### ISSUE THREAD

**Issue by g00chy** [g00chy/discord-bot#11]
理由はまだよくわからない。
ので、いったん記録するleave_banの機能ごと無効化した状態にする。

**Comment by t1una** [comment]
https://github.com/t1una/discord-bot/commit/933ec63c1aeb3f5e18b956f2961f3d3a865e24e8
いったん機能を無効化する。

**Comment by t1una** [comment]
https://scrapbox.io/keroxp/Gorm%E3%81%8C%E6%9C%AC%E7%95%AA%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E3%81%AE%E6%95%B0%E5%84%84%E4%BB%B6%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E6%B6%88%E3%81%9D%E3%81%86%E3%81%A8%E3%81%97%E3%81%9F%E8%A9%B1

原因これっぽい。（挙動似てるん）
